const localQuotes = [
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Sun Tzu" },
  { text: "Success is not final, failure is not fatal.", Author: "Winston Churchill" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Leonardo da Vinci" },
  { text: "Learning never exhausts the mind.", Author: "Confucius" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Albert Einstein" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Marie Curie" },
  { text: "Imagination is more important than knowledge.", Author: "Confucius" },
  { text: "Be yourself; everyone else is already taken.", Author: "Marie Curie" },
  { text: "Whatever you are, be a good one.", Author: "Maya Angelou" },
  { text: "Success is not final, failure is not fatal.", Author: "Sun Tzu" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Winston Churchill" },
  { text: "The secret of getting ahead is getting started.", Author: "Winston Churchill" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Maya Angelou" },
  { text: "Imagination is more important than knowledge.", Author: "" },
  { text: "Learning never exhausts the mind.", Author: "Albert Einstein" },
  { text: "Whatever you are, be a good one.", Author: "Albert Einstein" },
  { text: "The secret of getting ahead is getting started.", Author: "Abraham Lincoln" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Abraham Lincoln" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Leonardo da Vinci" },
  { text: "Success is not final, failure is not fatal.", Author: "Marie Curie" },
  { text: "Learning never exhausts the mind.", Author: "Abraham Lincoln" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Abraham Lincoln" },
  { text: "If you don't like something, change it.", Author: "Leonardo da Vinci" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Abraham Lincoln" },
  { text: "If you don't like something, change it.", Author: "Sun Tzu" },
  { text: "Learning never exhausts the mind.", Author: "Maya Angelou" },
  { text: "Be yourself; everyone else is already taken.", Author: "Marie Curie" },
  { text: "Be yourself; everyone else is already taken.", Author: "Oscar Wilde" },
  { text: "Whatever you are, be a good one.", Author: "Oscar Wilde" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Confucius" },
  { text: "The secret of getting ahead is getting started.", Author: "Sun Tzu" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Abraham Lincoln" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Sun Tzu" },
  { text: "Be yourself; everyone else is already taken.", Author: "Leonardo da Vinci" },
  { text: "Be yourself; everyone else is already taken.", Author: "Marie Curie" },
  { text: "Be yourself; everyone else is already taken.", Author: "Albert Einstein" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Abraham Lincoln" },
  { text: "Success is not final, failure is not fatal.", Author: "Leonardo da Vinci" },
  { text: "Success is not final, failure is not fatal.", Author: "Oscar Wilde" },
  { text: "Imagination is more important than knowledge.", Author: "Albert Einstein" },
  { text: "Whatever you are, be a good one.", Author: "Albert Einstein" },
  { text: "Whatever you are, be a good one.", Author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", Author: "Sun Tzu" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Mark Twain" },
  { text: "Success is not final, failure is not fatal.", Author: "Leonardo da Vinci" },
  { text: "Success is not final, failure is not fatal.", Author: "Confucius" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Abraham Lincoln" },
  { text: "Success is not final, failure is not fatal.", Author: "Winston Churchill" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Oscar Wilde" },
  { text: "Be yourself; everyone else is already taken.", Author: "Leonardo da Vinci" },
  { text: "Imagination is more important than knowledge.", Author: "Winston Churchill" },
  { text: "Imagination is more important than knowledge.", Author: "Albert Einstein" },
  { text: "The secret of getting ahead is getting started.", Author: "Oscar Wilde" },
  { text: "The secret of getting ahead is getting started.", Author: "Oscar Wilde" },
  { text: "Learning never exhausts the mind.", Author: "Marie Curie" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Maya Angelou" },
  { text: "Success is not final, failure is not fatal.", Author: "Sun Tzu" },
  { text: "If you don't like something, change it.", Author: "Oscar Wilde" },
  { text: "Imagination is more important than knowledge.", Author: "Confucius" },
  { text: "Whatever you are, be a good one.", Author: "Leonardo da Vinci" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Mark Twain" },
  { text: "Be yourself; everyone else is already taken.", Author: "Oscar Wilde" },
  { text: "Be yourself; everyone else is already taken.", Author: "Marie Curie" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Mark Twain" },
  { text: "Whatever you are, be a good one.", Author: "Maya Angelou" },
  { text: "Learning never exhausts the mind.", Author: "Abraham Lincoln" },
  { text: "Whatever you are, be a good one.", Author: "Winston Churchill" },
  { text: "The secret of getting ahead is getting started.", Author: "Leonardo da Vinci" },
  { text: "Be yourself; everyone else is already taken.", Author: "Oscar Wilde" },
  { text: "Imagination is more important than knowledge.", Author: "Winston Churchill" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Winston Churchill" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Mark Twain" },
  { text: "Success is not final, failure is not fatal.", Author: "Marie Curie" },
  { text: "Learning never exhausts the mind.", Author: "Confucius" },
  { text: "The secret of getting ahead is getting started.", Author: "Mark Twain" },
  { text: "Learning never exhausts the mind.", Author: "Confucius" },
  { text: "Whatever you are, be a good one.", Author: "Winston Churchill" },
  { text: "Learning never exhausts the mind.", Author: "Oscar Wilde" },
  { text: "Be yourself; everyone else is already taken.", Author: "Leonardo da Vinci" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Abraham Lincoln" },
  { text: "Be yourself; everyone else is already taken.", Author: "Mark Twain" },
  { text: "Whatever you are, be a good one.", Author: "Oscar Wilde" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Maya Angelou" },
  { text: "Success is not final, failure is not fatal.", Author: "Confucius" },
  { text: "If you don't like something, change it.", Author: "Oscar Wilde" },
  { text: "Whatever you are, be a good one.", Author: "Confucius" },
  { text: "Whatever you are, be a good one.", Author: "Albert Einstein" },
  { text: "Imagination is more important than knowledge.", Author: "Albert Einstein" },
  { text: "Be yourself; everyone else is already taken.", Author: "Maya Angelou" },
  { text: "Learning never exhausts the mind.", Author: "Abraham Lincoln" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Leonardo da Vinci" },
  { text: "Learning never exhausts the mind.", Author: "Albert Einstein" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Oscar Wilde" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Confucius" },
  { text: "The secret of getting ahead is getting started.", Author: "Marie Curie" },
  { text: "If you don't like something, change it.", Author: "Maya Angelou" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Abraham Lincoln" },
  { text: "Be yourself; everyone else is already taken.", Author: "Maya Angelou" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Leonardo da Vinci" },
  { text: "Success is not final, failure is not fatal.", Author: "Sun Tzu" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Leonardo da Vinci" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Mark Twain" },
  { text: "Whatever you are, be a good one.", Author: "Marie Curie" },
  { text: "The secret of getting ahead is getting started.", Author: "Confucius" },
  { text: "Learning never exhausts the mind.", Author: "Albert Einstein" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Confucius" },
  { text: "Imagination is more important than knowledge.", Author: "Marie Curie" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Marie Curie" },
  { text: "Learning never exhausts the mind.", Author: "Sun Tzu" },
  { text: "Success is not final, failure is not fatal.", Author: "Confucius" },
  { text: "Learning never exhausts the mind.", Author: "Confucius" },
  { text: "Be yourself; everyone else is already taken.", Author: "Confucius" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Oscar Wilde" },
  { text: "Learning never exhausts the mind.", Author: "Winston Churchill" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Albert Einstein" },
  { text: "Imagination is more important than knowledge.", Author: "Sun Tzu" },
  { text: "Be yourself; everyone else is already taken.", Author: "Albert Einstein" },
  { text: "Be yourself; everyone else is already taken.", Author: "Marie Curie" },
  { text: "Whatever you are, be a good one.", Author: "Mark Twain" },
  { text: "Learning never exhausts the mind.", Author: "Albert Einstein" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Winston Churchill" },
  { text: "The secret of getting ahead is getting started.", Author: "Oscar Wilde" },
  { text: "Be yourself; everyone else is already taken.", Author: "Mark Twain" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Confucius" },
  { text: "Learning never exhausts the mind.", Author: "Maya Angelou" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Abraham Lincoln" },
  { text: "Learning never exhausts the mind.", Author: "Sun Tzu" },
  { text: "The secret of getting ahead is getting started.", Author: "Winston Churchill" },
  { text: "Whatever you are, be a good one.", Author: "Sun Tzu" },
  { text: "If you don't like something, change it.", Author: "Winston Churchill" },
  { text: "Whatever you are, be a good one.", Author: "Marie Curie" },
  { text: "Whatever you are, be a good one.", Author: "Leonardo da Vinci" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Mark Twain" },
  { text: "Whatever you are, be a good one.", Author: "Marie Curie" },
  { text: "Learning never exhausts the mind.", Author: "Marie Curie" },
  { text: "The secret of getting ahead is getting started.", Author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Winston Churchill" },
  { text: "Success is not final, failure is not fatal.", Author: "Marie Curie" },
  { text: "If you don't like something, change it.", Author: "Maya Angelou" },
  { text: "Whatever you are, be a good one.", Author: "Oscar Wilde" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Maya Angelou" },
  { text: "Learning never exhausts the mind.", Author: "Leonardo da Vinci" },
  { text: "Imagination is more important than knowledge.", Author: "Abraham Lincoln" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Abraham Lincoln" },
  { text: "Learning never exhausts the mind.", Author: "Abraham Lincoln" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Leonardo da Vinci" },
  { text: "Imagination is more important than knowledge.", Author: "Winston Churchill" },
  { text: "If you don't like something, change it.", Author: "Confucius" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Albert Einstein" },
  { text: "If you don't like something, change it.", Author: "Oscar Wilde" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Confucius" },
  { text: "Whatever you are, be a good one.", Author: "Albert Einstein" },
  { text: "Success is not final, failure is not fatal.", Author: "Winston Churchill" },
  { text: "Whatever you are, be a good one.", Author: "Confucius" },
  { text: "Whatever you are, be a good one.", Author: "Winston Churchill" },
  { text: "Success is not final, failure is not fatal.", Author: "Mark Twain" },
  { text: "Imagination is more important than knowledge.", Author: "Marie Curie" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Mark Twain" },
  { text: "Success is not final, failure is not fatal.", Author: "Abraham Lincoln" },
  { text: "Learning never exhausts the mind.", Author: "Albert Einstein" },
  { text: "Success is not final, failure is not fatal.", Author: "Winston Churchill" },
  { text: "If you don't like something, change it.", Author: "Abraham Lincoln" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Leonardo da Vinci" },
  { text: "Whatever you are, be a good one.", Author: "Winston Churchill" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Winston Churchill" },
  { text: "Be yourself; everyone else is already taken.", Author: "Confucius" },
  { text: "Success is not final, failure is not fatal.", Author: "Sun Tzu" },
  { text: "Success is not final, failure is not fatal.", Author: "Mark Twain" },
  { text: "Be yourself; everyone else is already taken.", Author: "Abraham Lincoln" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Marie Curie" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Abraham Lincoln" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", Author: "Maya Angelou" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Confucius" },
  { text: "Whatever you are, be a good one.", Author: "Confucius" },
  { text: "Learning never exhausts the mind.", Author: "Winston Churchill" },
  { text: "The secret of getting ahead is getting started.", Author: "Albert Einstein" },
  { text: "The secret of getting ahead is getting started.", Author: "Mark Twain" },
  { text: "Be yourself; everyone else is already taken.", Author: "Confucius" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Oscar Wilde" },
  { text: "If you don't like something, change it.", Author: "Winston Churchill" },
  { text: "If you don't like something, change it.", Author: "Abraham Lincoln" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Mark Twain" },
  { text: "Be yourself; everyone else is already taken.", Author: "Mark Twain" },
  { text: "Be yourself; everyone else is already taken.", Author: "Abraham Lincoln" },
  { text: "Be yourself; everyone else is already taken.", Author: "Marie Curie" },
  { text: "Success is not final, failure is not fatal.", Author: "Abraham Lincoln" },
  { text: "If you don't like something, change it.", Author: "Marie Curie" },
  { text: "Imagination is more important than knowledge.", Author: "Winston Churchill" },
  { text: "The secret of getting ahead is getting started.", Author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Maya Angelou" },
  { text: "Learning never exhausts the mind.", Author: "Abraham Lincoln" },
  { text: "Whatever you are, be a good one.", Author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Oscar Wilde" },
  { text: "Success is not final, failure is not fatal.", Author: "Albert Einstein" },
  { text: "Whatever you are, be a good one.", Author: "Albert Einstein" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Confucius" },
  { text: "If you don't like something, change it.", Author: "Oscar Wilde" },
  { text: "Be yourself; everyone else is already taken.", Author: "Leonardo da Vinci" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Albert Einstein" },
  { text: "Success is not final, failure is not fatal.", Author: "Marie Curie" },
  { text: "Learning never exhausts the mind.", Author: "Abraham Lincoln" },
  { text: "The secret of getting ahead is getting started.", Author: "Confucius" },
  { text: "Whatever you are, be a good one.", Author: "Confucius" },
  { text: "If you don't like something, change it.", Author: "Marie Curie" },
  { text: "Be yourself; everyone else is already taken.", Author: "Marie Curie" },
  { text: "Learning never exhausts the mind.", Author: "Maya Angelou" },
  { text: "Success is not final, failure is not fatal.", Author: "Confucius" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Maya Angelou" },
  { text: "If you don't like something, change it.", Author: "Confucius" },
  { text: "Imagination is more important than knowledge.", Author: "Sun Tzu" },
  { text: "If you don't like something, change it.", Author: "Leonardo da Vinci" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Leonardo da Vinci" },
  { text: "Whatever you are, be a good one.", Author: "Maya Angelou" },
  { text: "If you don't like something, change it.", Author: "Oscar Wilde" },
  { text: "The secret of getting ahead is getting started.", Author: "Albert Einstein" },
  { text: "Imagination is more important than knowledge.", Author: "Oscar Wilde" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Albert Einstein" },
  { text: "The secret of getting ahead is getting started.", Author: "Leonardo da Vinci" },
  { text: "Success is not final, failure is not fatal.", Author: "Winston Churchill" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Abraham Lincoln" },
  { text: "Be yourself; everyone else is already taken.", Author: "Albert Einstein" },
  { text: "Be yourself; everyone else is already taken.", Author: "Sun Tzu" },
  { text: "If you don't like something, change it.", Author: "Abraham Lincoln" },
  { text: "If you don't like something, change it.", Author: "Abraham Lincoln" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Winston Churchill" },
  { text: "Success is not final, failure is not fatal.", Author: "Marie Curie" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Oscar Wilde" },
  { text: "If you don't like something, change it.", Author: "Oscar Wilde" },
  { text: "Imagination is more important than knowledge.", Author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", Author: "Oscar Wilde" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Marie Curie" },
  { text: "Imagination is more important than knowledge.", Author: "Leonardo da Vinci" },
  { text: "The secret of getting ahead is getting started.", Author: "Marie Curie" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Leonardo da Vinci" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Confucius" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Marie Curie" },
  { text: "Be yourself; everyone else is already taken.", Author: "Abraham Lincoln" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Marie Curie" },
  { text: "Learning never exhausts the mind.", Author: "Leonardo da Vinci" },
  { text: "Learning never exhausts the mind.", Author: "Confucius" },
  { text: "Success is not final, failure is not fatal.", Author: "Oscar Wilde" },
  { text: "Success is not final, failure is not fatal.", Author: "Winston Churchill" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Marie Curie" },
  { text: "Imagination is more important than knowledge.", Author: "Oscar Wilde" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Oscar Wilde" },
  { text: "Imagination is more important than knowledge.", Author: "Sun Tzu" },
  { text: "Imagination is more important than knowledge.", Author: "Albert Einstein" },
  { text: "Learning never exhausts the mind.", Author: "Maya Angelou" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Albert Einstein" },
  { text: "Be yourself; everyone else is already taken.", Author: "Marie Curie" },
  { text: "Imagination is more important than knowledge.", Author: "Maya Angelou" },
  { text: "Be yourself; everyone else is already taken.", Author: "Leonardo da Vinci" },
  { text: "Whatever you are, be a good one.", Author: "Oscar Wilde" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Oscar Wilde" },
  { text: "If you don't like something, change it.", Author: "Maya Angelou" },
  { text: "Success is not final, failure is not fatal.", Author: "Marie Curie" },
  { text: "The secret of getting ahead is getting started.", Author: "Winston Churchill" },
  { text: "Be yourself; everyone else is already taken.", Author: "Abraham Lincoln" },
  { text: "Learning never exhausts the mind.", Author: "Maya Angelou" },
  { text: "Learning never exhausts the mind.", Author: "Confucius" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Marie Curie" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Maya Angelou" },
  { text: "Imagination is more important than knowledge.", Author: "Maya Angelou" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Confucius" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Sun Tzu" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", Author: "Sun Tzu" },
  { text: "The secret of getting ahead is getting started.", Author: "Leonardo da Vinci" },
  { text: "The secret of getting ahead is getting started.", Author: "Sun Tzu" },
  { text: "Imagination is more important than knowledge.", Author: "Albert Einstein" },
  { text: "Imagination is more important than knowledge.", Author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", Author: "Winston Churchill" },
  { text: "The secret of getting ahead is getting started.", Author: "Oscar Wilde" },
  { text: "Whatever you are, be a good one.", Author: "Winston Churchill" },
  { text: "Be yourself; everyone else is already taken.", Author: "Sun Tzu" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Abraham Lincoln" },
  { text: "The secret of getting ahead is getting started.", Author: "Oscar Wilde" },
  { text: "Be yourself; everyone else is already taken.", Author: "Winston Churchill" },
  { text: "Whatever you are, be a good one.", Author: "Leonardo da Vinci" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Maya Angelou" },
  { text: "If you don't like something, change it.", Author: "Abraham Lincoln" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Sun Tzu" },
  { text: "Whatever you are, be a good one.", Author: "Oscar Wilde" },
  { text: "Learning never exhausts the mind.", Author: "Maya Angelou" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Mark Twain" },
  { text: "Nothing in life is to be feared, it is only to be understood.", Author: "Marie Curie" },
  { text: "If you don't like something, change it.", Author: "Winston Churchill" },
  { text: "Imagination is more important than knowledge.", Author: "Maya Angelou" },
  { text: "Success is not final, failure is not fatal.", Author: "Abraham Lincoln" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Oscar Wilde" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Leonardo da Vinci" },
  { text: "Success is not final, failure is not fatal.", Author: "Albert Einstein" },
  { text: "Success is not final, failure is not fatal.", Author: "Confucius" },
  { text: "The secret of getting ahead is getting started.", Author: "Confucius" },
  { text: "Be yourself; everyone else is already taken.", Author: "Maya Angelou" },
  { text: "It does not matter how slowly you go as long as you do not stop.", Author: "Winston Churchill" },
  { text: "If you are far from the enemy, make him believe you are near.", Author: "Albert Einstein" },
  { text: "Success is not final, failure is not fatal.", Author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", Author: "Maya Angelou" }
];